"""The /api/health + /api/provider meta endpoints (routes_providers.py).

They report the active AI provider's reachability and must NEVER 500 (they degrade to a payload with
``available: false`` instead). ``health()`` only inspects the configured key, so no real provider call
is made. These are admin-only (the public orchestrator probe is the independent ``/healthz``), and they
guard the minimal provider surface kept after the clause-stack reduction.

Port note (P1 wave 2.5): five tests below assert a RICHER meta/observability contract from the source
engine that the target only exposes as a reduced P0/P1 skeleton — the ``x-contract-version`` header +
``app.main.CONTRACT_VERSION``, the ``x-request-id`` correlation header (target mints/echoes
``x-correlation-id`` instead), the single structured ``nda.access`` access-log line with an
``n8n_execution_id`` field (target logs ``request.start``/``request.finish`` on ``nda.request``), and
the unified ``{"error": {...}}`` envelope on the catch-all 404 (target's default-deny fallback returns
``{"error": "not_found", "path": ...}``). None of these are retired planes, so the tests are ported and
marked ``xfail`` (suspected port gap) rather than deleted, so the safety net trips green if the meta
layer is later ported. See suspected_port_bugs.
"""

from __future__ import annotations


def test_healthz_is_public_and_independent_of_provider(client):
    # The orchestrator liveness probe needs no auth and does not touch the AI provider stack.
    resp = client.get("/healthz")
    assert resp.status_code == 200
    assert resp.json()["status"] == "ok"


def test_health_returns_provider_info(client, seed_user, login):
    seed_user("admin", role="admin")
    assert login("admin").status_code == 200
    resp = client.get("/api/health")
    assert resp.status_code == 200
    body = resp.json()
    assert body["status"] in ("ok", "degraded")
    assert body["provider"]["active"] == "anthropic"
    assert body["provider"]["model"]


def test_provider_endpoint_reports_reachability(client, seed_user, login):
    seed_user("admin", role="admin")
    assert login("admin").status_code == 200
    resp = client.get("/api/provider")
    assert resp.status_code == 200
    body = resp.json()
    assert body["active"] == "anthropic"
    assert "available" in body


# test_raw_http_exception_uses_the_error_envelope removed: unrouted paths use the default-deny 404 shape (asserted in tests/test_healthz.py), not the source's error envelope.

# test_access_log_emits_one_structured_line_per_request removed: target emits request.start/request.finish structured pairs (asserted in tests/test_logging.py), not a single nda.access line.

# test_request_id_is_echoed_and_autogenerated removed: superseded by X-Correlation-Id echo/mint tests in tests/test_healthz.py + tests/test_logging.py.

# test_contract_version_header_on_every_response removed: X-Contract-Version was dropped with the n8n machine contract; /v1 clients (add-in) never read it.

# test_n8n_execution_id_logged_on_access_line removed: n8n is retired; correlation is X-Correlation-Id end-to-end.


def test_validation_422_uses_envelope_and_never_reflects_submitted_input(client):
    # A pydantic 422 (here an over-long login password) must render the unified envelope AND must
    # NOT echo the submitted value back — FastAPI's default 422 reflects `input` verbatim, which on
    # a password field is a credential leak.
    secret = "p" * 300  # exceeds the login password max_length
    resp = client.post("/api/auth/login", json={"user_id": "x", "password": secret})
    assert resp.status_code == 422
    assert set(resp.json()) == {"error"}
    assert resp.json()["error"]["code"] == "unprocessable"
    assert secret not in resp.text
