"""baseline current schema

The SINGLE squashed baseline for the NDA Assistant data layer (P1 port). It creates the full KEPT
schema in one revision — the source engine's 23-migration chain was collapsed here after dropping the
retired SIGNED-plane + n8n-doorway tables (principal_nonces, allowed_accounts, nda_bot_request,
nda_bot_event, nda_bot_envelope). ``Base.metadata.create_all`` is schema-equivalent to
``alembic upgrade head`` from this file — asserted by tests/test_migrations.py.

Generated by Alembic autogenerate from ``Base.metadata`` (SQLite, render_as_batch), then hand-fixed:
``sa.Text()`` on the JSONB variant (autogenerate emits a bare ``Text()``), and the revision id pinned
to ``0001_baseline`` (matches app.db_migrate._BASELINE_REVISION for the pre-Alembic stamp path).

Revision ID: 0001_baseline
Revises:
Create Date: 2026-07-03

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('auth_audit_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=True),
    sa.Column('actor_principal', sa.String(length=128), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_audit_events_org_id'), ['org_id'], unique=False)

    op.create_table('contracts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), server_default='00000000000000000000000000000001', nullable=False),
    sa.Column('contract_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('counterparty_name', sa.String(length=255), nullable=False),
    sa.Column('doc_sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lifecycle_status', sa.String(length=32), server_default='draft', nullable=False),
    sa.Column('lifecycle_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lifecycle_status_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_user_id', sa.String(length=32), nullable=True),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notice_period_days', sa.Integer(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('renewal_term_months', sa.Integer(), nullable=True),
    sa.Column('renewal_terms_json', sa.Text(), server_default='{}', nullable=False),
    sa.Column('docusign_envelope_id', sa.String(length=128), nullable=True),
    sa.Column('latest_risk_tier', sa.String(length=16), server_default='', nullable=False),
    sa.Column('latest_adherence_score', sa.Float(), nullable=True),
    sa.Column('value_usd', sa.Float(), nullable=True),
    sa.Column('last_reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contracts_doc_sha256'), ['doc_sha256'], unique=False)
        batch_op.create_index('ix_contracts_lifecycle_expiration', ['lifecycle_status', 'expiration_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_lifecycle_status'), ['lifecycle_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('document_blob',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('bytes', sa.LargeBinary(), nullable=True),
    sa.Column('storage_uri', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    op.create_table('engine_review_jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), server_default='00000000000000000000000000000001', nullable=False),
    sa.Column('principal_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claim_token', sa.String(length=32), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('playbook_version', sa.String(length=64), nullable=True),
    sa.Column('source_channel', sa.String(length=32), nullable=False),
    sa.Column('doc_filename', sa.String(length=512), nullable=False),
    sa.Column('doc_sha256', sa.String(length=64), nullable=False),
    sa.Column('norm_sha256', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('incoming_text', sa.Text(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('review_id', sa.String(length=32), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engine_review_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engine_review_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_review_jobs_org_id'), ['org_id'], unique=False)
        batch_op.create_index('ix_engine_review_jobs_status_created', ['status', 'created_at'], unique=False)

    op.create_table('nda_idempotency_key',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), server_default='00000000000000000000000000000001', nullable=False),
    sa.Column('principal_id', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('review_id', sa.String(length=32), nullable=True),
    sa.Column('response_body', sa.LargeBinary(), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'principal_id', 'purpose', 'key', name='uq_nda_idempotency_principal_purpose_key')
    )
    with op.batch_alter_table('nda_idempotency_key', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nda_idempotency_key_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_nda_idempotency_key_org_id'), ['org_id'], unique=False)

    op.create_table('orgs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ref_counterparty_type',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('ref_jurisdiction',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('ref_mutuality',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('ref_template_variant',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('ref_token_scope',
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('templates',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('file_format', sa.String(length=16), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('clause_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engine_reviews',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('contract_id', sa.String(length=32), nullable=True),
    sa.Column('org_id', sa.String(length=32), server_default='00000000000000000000000000000001', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_channel', sa.String(length=32), nullable=False),
    sa.Column('actor_user_id', sa.String(length=32), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('playbook_version', sa.String(length=32), nullable=False),
    sa.Column('perspective', sa.String(length=32), nullable=False),
    sa.Column('risk_tier', sa.String(length=16), nullable=False),
    sa.Column('adherence_score', sa.Float(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('doc_filename', sa.String(length=512), nullable=False),
    sa.Column('doc_sha256', sa.String(length=64), nullable=False),
    sa.Column('norm_sha256', sa.String(length=64), nullable=False),
    sa.Column('playbook_release', sa.String(length=64), nullable=True),
    sa.Column('payload_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engine_reviews', schema=None) as batch_op:
        batch_op.create_index('ix_engine_reviews_contract_created', ['contract_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_reviews_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_reviews_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_reviews_doc_sha256'), ['doc_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_reviews_norm_sha256'), ['norm_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_reviews_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_reviews_risk_tier'), ['risk_tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_reviews_source_channel'), ['source_channel'], unique=False)

    op.create_table('service_account_keys',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('principal_id', sa.String(length=32), nullable=False),
    sa.Column('entitlements_json', sa.Text(), nullable=False),
    sa.Column('rate_per_min', sa.Integer(), nullable=True),
    sa.Column('monthly_cost_cap_usd', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_account_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_account_keys_key_hash'), ['key_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_service_account_keys_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_account_keys_principal_id'), ['principal_id'], unique=False)

    op.create_table('template',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('jurisdiction_code', sa.String(length=32), nullable=False),
    sa.Column('counterparty_type_code', sa.String(length=32), nullable=False),
    sa.Column('mutuality_code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(counterparty_type_code = 'Individual' AND mutuality_code IN ('Mutual','Unilateral')) OR (counterparty_type_code <> 'Individual' AND mutuality_code = 'NotApplicable')", name='ck_template_mutuality_scope'),
    sa.ForeignKeyConstraint(['counterparty_type_code'], ['ref_counterparty_type.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['jurisdiction_code'], ['ref_jurisdiction.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['mutuality_code'], ['ref_mutuality.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jurisdiction_code', 'counterparty_type_code', 'mutuality_code', name='uq_template_dimensions')
    )
    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_template_org_id'), ['org_id'], unique=False)

    op.create_table('token',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('placeholder', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('scope_code', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scope_code'], ['ref_token_scope.code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('placeholder')
    )
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_scope_code'), ['scope_code'], unique=False)

    op.create_table('user_accounts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('team', sa.String(length=64), nullable=True),
    sa.Column('can_view_all_docs', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('can_view_all_spend', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('can_manage_permissions', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('session_epoch', sa.Integer(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_accounts_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_accounts_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_accounts_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_accounts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_accounts_team'), ['team'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_accounts_user_id'), ['user_id'], unique=True)

    op.create_table('identity_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('revocation_epoch', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('identity_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identity_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_identity_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('review_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('contract_id', sa.String(length=32), nullable=True),
    sa.Column('review_id', sa.String(length=32), nullable=True),
    sa.Column('org_id', sa.String(length=32), server_default='00000000000000000000000000000001', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['engine_reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_events', schema=None) as batch_op:
        batch_op.create_index('ix_review_events_contract_created', ['contract_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_events_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_events_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_events_review_id'), ['review_id'], unique=False)

    op.create_table('service_account_usage',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('key_id', sa.String(length=32), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['key_id'], ['service_account_keys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_id', 'period', name='uq_service_account_usage_key_period')
    )
    with op.batch_alter_table('service_account_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_account_usage_key_id'), ['key_id'], unique=False)

    op.create_table('template_version',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('template_id', sa.String(length=32), nullable=False),
    sa.Column('variant_code', sa.String(length=32), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('blob_id', sa.String(length=32), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['blob_id'], ['document_blob.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_code'], ['ref_template_variant.code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'variant_code', 'version_no', name='uq_template_version_variant_no')
    )
    with op.batch_alter_table('template_version', schema=None) as batch_op:
        batch_op.create_index('ix_template_version_current', ['template_id', 'variant_code', 'is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_template_version_template_id'), ['template_id'], unique=False)

    op.create_table('token_template',
    sa.Column('token_id', sa.String(length=32), nullable=False),
    sa.Column('template_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['token_id'], ['token.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id', 'template_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_template')
    with op.batch_alter_table('template_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_template_version_template_id'))
        batch_op.drop_index('ix_template_version_current')

    op.drop_table('template_version')
    with op.batch_alter_table('service_account_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_account_usage_key_id'))

    op.drop_table('service_account_usage')
    with op.batch_alter_table('review_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_events_review_id'))
        batch_op.drop_index(batch_op.f('ix_review_events_org_id'))
        batch_op.drop_index(batch_op.f('ix_review_events_contract_id'))
        batch_op.drop_index('ix_review_events_contract_created')

    op.drop_table('review_events')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token_hash'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('identity_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identity_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_identity_sessions_token_hash'))

    op.drop_table('identity_sessions')
    with op.batch_alter_table('user_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_accounts_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_accounts_team'))
        batch_op.drop_index(batch_op.f('ix_user_accounts_status'))
        batch_op.drop_index(batch_op.f('ix_user_accounts_role'))
        batch_op.drop_index(batch_op.f('ix_user_accounts_org_id'))
        batch_op.drop_index(batch_op.f('ix_user_accounts_email'))

    op.drop_table('user_accounts')
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_scope_code'))

    op.drop_table('token')
    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_template_org_id'))

    op.drop_table('template')
    with op.batch_alter_table('service_account_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_account_keys_principal_id'))
        batch_op.drop_index(batch_op.f('ix_service_account_keys_org_id'))
        batch_op.drop_index(batch_op.f('ix_service_account_keys_key_hash'))

    op.drop_table('service_account_keys')
    with op.batch_alter_table('engine_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engine_reviews_source_channel'))
        batch_op.drop_index(batch_op.f('ix_engine_reviews_risk_tier'))
        batch_op.drop_index(batch_op.f('ix_engine_reviews_org_id'))
        batch_op.drop_index(batch_op.f('ix_engine_reviews_norm_sha256'))
        batch_op.drop_index(batch_op.f('ix_engine_reviews_doc_sha256'))
        batch_op.drop_index(batch_op.f('ix_engine_reviews_created_at'))
        batch_op.drop_index(batch_op.f('ix_engine_reviews_contract_id'))
        batch_op.drop_index('ix_engine_reviews_contract_created')

    op.drop_table('engine_reviews')
    op.drop_table('templates')
    op.drop_table('ref_token_scope')
    op.drop_table('ref_template_variant')
    op.drop_table('ref_mutuality')
    op.drop_table('ref_jurisdiction')
    op.drop_table('ref_counterparty_type')
    op.drop_table('orgs')
    with op.batch_alter_table('nda_idempotency_key', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nda_idempotency_key_org_id'))
        batch_op.drop_index(batch_op.f('ix_nda_idempotency_key_created_at'))

    op.drop_table('nda_idempotency_key')
    with op.batch_alter_table('engine_review_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_engine_review_jobs_status_created')
        batch_op.drop_index(batch_op.f('ix_engine_review_jobs_org_id'))
        batch_op.drop_index(batch_op.f('ix_engine_review_jobs_created_at'))

    op.drop_table('engine_review_jobs')
    op.drop_table('document_blob')
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_contracts_org_id'))
        batch_op.drop_index(batch_op.f('ix_contracts_lifecycle_status'))
        batch_op.drop_index('ix_contracts_lifecycle_expiration')
        batch_op.drop_index(batch_op.f('ix_contracts_doc_sha256'))

    op.drop_table('contracts')
    with op.batch_alter_table('auth_audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_audit_events_org_id'))
        batch_op.drop_index(batch_op.f('ix_auth_audit_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_auth_audit_events_action'))

    op.drop_table('auth_audit_events')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
